<a href="https://colab.research.google.com/github/abhayjr11/PysparkPractice_ground/blob/main/PySpark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

# Create database
conn = sqlite3.connect('interview.db')

cursor = conn.cursor()

In [ ]:
cursor.execute("""
CREATE TABLE orders(
order_id INTEGER PRIMARY KEY,
customer_id TEXT,
customer_name TEXT,
city TEXT,
product TEXT,
category TEXT,
quantity INTEGER,
price REAL,
order_date DATE,
salesperson TEXT,
payment_mode TEXT,
status TEXT
)
""")

In [ ]:
data = [
(1001,'C001','John','Delhi','Laptop','Electronics',2,65000,'2024-01-05','Rahul','UPI','Completed'),
(1002,'C002','Alice','Mumbai','Mobile','Electronics',1,30000,'2024-01-06','Neha','Card','Completed'),
(1003,'C003','Bob','Delhi','Keyboard','Accessories',3,1200,'2024-01-07','Rahul','Cash','Returned'),
(1004,'C001','John','Delhi','Mouse','Accessories',2,800,'2024-01-08','Rahul','UPI','Completed'),
(1005,'C004','David','Pune','Monitor','Electronics',1,15000,'2024-01-09','Riya','Card','Pending'),
(1006,'C005','Emma','Mumbai','Chair','Furniture',2,7000,'2024-01-10','Neha','Cash','Completed'),
(1007,'C002','Alice','Mumbai','Table','Furniture',1,10000,'2024-01-11','Neha','UPI','Completed'),
(1008,'C006','Tom','Hyderabad','Laptop','Electronics',1,65000,'2024-01-12','Amit','Card','Completed'),
(1009,'C007','Sophia','Delhi','Keyboard','Accessories',4,1200,'2024-01-13','Rahul','Cash','Completed'),
(1010,'C001','John','Delhi','Laptop','Electronics',1,65000,'2024-01-14','Rahul','UPI','Completed'),
(1011,'C003','Bob','Chennai','Monitor','Electronics',2,15000,'2024-01-15','Amit','Card','Returned'),
(1012,'C008','Chris','Pune','Mobile','Electronics',2,30000,'2024-01-16','Riya','UPI','Completed'),
(1013,'C009','Mia','Delhi','Mouse','Accessories',5,800,'2024-01-17','Rahul','Cash','Pending'),
(1014,'C010','James','Delhi','Laptop','Electronics',1,65000,'2024-01-18','Rahul','Card','Completed'),
(1015,'C005','Emma','Mumbai','Chair','Furniture',1,7000,'2024-01-19','Neha','Cash','Completed'),
(1016,'C004','David','Pune','Laptop','Electronics',2,65000,'2024-01-20','Riya','Card','Completed'),
(1017,'C002','Alice','Mumbai','Mobile','Electronics',3,30000,'2024-01-21','Neha','UPI','Completed'),
(1018,'C003','Bob','Delhi','Mouse','Accessories',2,800,'2024-01-22','Rahul','Cash','Returned'),
(1019,'C011','Liam','Hyderabad','Table','Furniture',2,10000,'2024-01-23','Amit','Card','Completed'),
(1020,'C012','Olivia','Delhi','Laptop','Electronics',1,65000,'2024-01-24','Rahul','UPI','Completed')
]

cursor.executemany(
"INSERT INTO orders VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",
data
)

conn.commit()

In [ ]:
pd.read_sql("select * from orders",conn).head(1)

,order_id,customer_id,customer_name,city,product,category,quantity,price,order_date,salesperson,payment_mode,status
0,1001,C001,John,Delhi,Laptop,Electronics,2,65000.0,2024-01-05,Rahul,UPI,Completed

In [ ]:
#Find orders from Delhi.

pd.read_sql("select * from orders where city == 'Delhi'",conn).head(1)

,order_id,customer_id,customer_name,city,product,category,quantity,price,order_date,salesperson,payment_mode,status
0,1001,C001,John,Delhi,Laptop,Electronics,2,65000.0,2024-01-05,Rahul,UPI,Completed

In [ ]:
#Find orders after 15 Jan.
pd.read_sql("select * from orders where order_date>'2024-01-15';", conn).head(1)

,order_id,customer_id,customer_name,city,product,category,quantity,price,order_date,salesperson,payment_mode,status
0,1012,C008,Chris,Pune,Mobile,Electronics,2,30000.0,2024-01-16,Riya,UPI,Completed

In [ ]:
# Show unique cities.
pd.read_sql("select distinct(city) from orders;", conn).head(1)

    city
0  Delhi

In [ ]:
#Count distinct customers.
pd.read_sql("select count(distinct(customer_id)) from orders;", conn)

   count(distinct(customer_id))
0                            12

In [ ]:
#Find total sales.
pd.read_sql("select sum(price*quantity) as tsales from orders;", conn)

     tsales
0  811600.0

In [ ]:
#Find average price.
pd.read_sql("select avg(price) as avg_prc from orders;", conn)

   avg_prc
0  27440.0

In [ ]:
#Find average quantity.
pd.read_sql("select avg(quantity) as avg_q from orders;", conn)

   avg_q
0   1.95

In [ ]:
#Find total revenue for Electronics.
pd.read_sql("select sum(price*quantity) as t_s_e from orders where category == 'Electronics';", conn)

      t_s_e
0  745000.0

In [ ]:
#Total sales by city.
pd.read_sql("select city, sum(price*quantity) as t_s_b_c from orders group by city;", conn)

        city   t_s_b_c
0    Chennai   30000.0
1      Delhi  340600.0
2  Hyderabad   85000.0
3     Mumbai  151000.0
4       Pune  205000.0

In [ ]:
#Total revenue by customer.
pd.read_sql("select customer_id,sum(price*quantity) as r_b_c from orders group by customer_id;", conn).head(1)

  customer_id     r_b_c
0        C001  196600.0

In [ ]:
#Number of orders per city.
pd.read_sql("select city, count(customer_id) as t_c_b_c from orders group by city;", conn)

        city  t_c_b_c
0    Chennai        1
1      Delhi        9
2  Hyderabad        2
3     Mumbai        5
4       Pune        3

In [ ]:
#Average price by category.
pd.read_sql("select category, avg(price) as a_p_b_c from orders group by category;", conn)

      category       a_p_b_c
0  Accessories    960.000000
1  Electronics  46363.636364
2    Furniture   8500.000000

In [ ]:
#Highest revenue city.
pd.read_sql("select city, sum(price*quantity) as max_rev from orders group by city order by max_rev desc limit 1;", conn)

    city   max_rev
0  Delhi  340600.0

In [ ]:
#Lowest revenue city.
pd.read_sql("select city, sum(price*quantity) as max_rev from orders group by city order by max_rev limit 1;", conn)

      city  max_rev
0  Chennai  30000.0

In [ ]:
#Product sold most.
pd.read_sql("select product, count(quantity) from orders group by product order by count(quantity) desc limit 1;", conn)

  product  count(quantity)
0  Laptop                6

In [ ]:
#Category generating highest revenue.
pd.read_sql("select category, sum(price*quantity) as rev from orders group by category order by rev desc limit 1;", conn)

      category       rev
0  Electronics  745000.0

In [ ]:
#Orders by salesperson.
pd.read_sql("select salesperson, sum(quantity) as t_ord from orders group by salesperson ;", conn)

  salesperson  t_ord
0        Amit      5
1        Neha      8
2       Rahul     21
3        Riya      5

In [ ]:
#Revenue by payment mode.
pd.read_sql("select * from orders where order_date>'2024-01-15';", conn).head(1)
pd.read_sql("select payment_mode, sum(price*quantity)as t_rev from orders group by payment_mode;", conn)

  payment_mode     t_rev
0         Card  355000.0
1         Cash   35000.0
2          UPI  421600.0

In [ ]:
# Customers with more than one order.
pd.read_sql("select customer_id , sum(quantity) from orders group by customer_id having sum(quantity) >1 ;", conn).head(1)

  customer_id  sum(quantity)
0        C001              5

In [ ]:
#Cities having revenue above ₹100000.
pd.read_sql("select city , sum(price*quantity) as t_rev from orders group by city having sum(price*quantity) > 100000 ;", conn)

     city     t_rev
0   Delhi  340600.0
1  Mumbai  151000.0
2    Pune  205000.0

In [ ]:
# Categories with more than five orders.
pd.read_sql("select category, sum(quantity) as t_qun from orders group by category having sum(quantity)>5  ;", conn)

      category  t_qun
0  Accessories     16
1  Electronics     17
2    Furniture      6

In [ ]:
#Salespersons with revenue above ₹200000.
pd.read_sql("select salesperson, sum(quantity * price ) as t_rev from orders group by salesperson having sum(quantity * price )>200000  ;", conn)

  salesperson     t_rev
0       Rahul  340600.0
1        Riya  205000.0

In [ ]:
#Sort by customer then date.
pd.read_sql("select customer_id, order_date from orders order by customer_id , order_date;", conn).head(1)

  customer_id  order_date
0        C001  2024-01-05

In [ ]:
#Uppercase customer names.
pd.read_sql("select upper(customer_name) as customer_name from orders;", conn).head(1)

  customer_name
0          JOHN

In [ ]:
# Lowercase city names.
pd.read_sql("select lower(city) as city from orders;", conn).head(1)

    city
0  delhi

In [ ]:
#Length of product names.
pd.read_sql("select product, length(product) as pro_len from orders group by product;", conn).head(1)

  product  pro_len
0   Chair        5

In [ ]:
#First three letters of customer names.
pd.read_sql("select upper(substr(customer_name,1,3)) as abb from orders ;", conn).head(1)

   abb
0  JOH

In [ ]:
# Replace Laptop with Notebook
pd.read_sql("select product, replace(product , 'Laptop' , 'Notebook') as updated_pro from orders ;", conn).head(1)

  product updated_pro
0  Laptop    Notebook

In [ ]:
# Concatenate customer and city.
pd.read_sql("select customer_name , city , customer_name || ' ' || city as cus_cit from orders ;", conn).head(1)

  customer_name   city     cus_cit
0          John  Delhi  John Delhi

In [ ]:
#Customers whose name starts with J.
pd.read_sql("select customer_name from orders where customer_name like'j%';", conn)

  customer_name
0          John
1          John
2          John
3         James

In [ ]:
#Customers ending with a.
pd.read_sql("select customer_name from orders where customer_name like '%a' ;", conn).head(1)

  customer_name
0          Emma

In [ ]:
#Product containing "top".
pd.read_sql("select product from orders where product like '%top%' ;", conn).head(1)

  product
0  Laptop

In [ ]:
#Reverse customer names.
conn.create_function("reve",1,lambda x : x[::-1] if x else None )
pd.read_sql("select customer_name, reve(customer_name) as rev  from orders ;", conn).head(1)

  customer_name   rev
0          John  nhoJ

In [ ]:
pd.read_sql("select * from orders ;", conn).head(1)

,order_id,customer_id,customer_name,city,product,category,quantity,price,order_date,salesperson,payment_mode,status
0,1001,C001,John,Delhi,Laptop,Electronics,2,65000.0,2024-01-05,Rahul,UPI,Completed

In [ ]:
#First order.
#Last order.
pd.read_sql("select max(order_date) as l_order, min(order_date) as f_order from orders ;", conn).head(1)

      l_order     f_order
0  2024-01-24  2024-01-05

In [ ]:
#Orders between two dates.
pd.read_sql("select sum(quantity) as t_order from orders where order_date between '2024-01-24' AND '2024-01-24' ;", conn)

   t_order
0        1

In [ ]:
pd.read_sql("select * from orders ;", conn).head(1)

,order_id,customer_id,customer_name,city,product,category,quantity,price,order_date,salesperson,payment_mode,status
0,1001,C001,John,Delhi,Laptop,Electronics,2,65000.0,2024-01-05,Rahul,UPI,Completed

In [ ]:
#Change the status of order_id = 1005 to Completed.
cursor.execute("UPDATE orders SET status = 'Returned' where order_id = 1003 ;")
pd.read_sql("select * from orders",conn).head(1)

,order_id,customer_id,customer_name,city,product,category,quantity,price,order_date,salesperson,payment_mode,status
0,1001,C001,John,Delhi,Laptop,Electronics,2,65000.0,2024-01-05,Rahul,UPI,Completed